apiVersion: v2
name: aioc-hospital-frontend
description: AIOC Hospital React Frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: aioc-hospital-base
    version: "0.1.0"
    repository: "file://../../aioc-hospital-base"
